import jsPDF from 'jspdf'
import { Receipt } from '@/types/inventory'

export interface ReceiptPDFData {
  receipt: Receipt
  productName: string
  warehouseName?: string
  supplierName?: string
}

export function generateReceiptPDF(data: ReceiptPDFData): void {
  const { receipt, productName, warehouseName, supplierName } = data
  
  // Create new PDF document
  const doc = new jsPDF()
  
  // Set font sizes
  const titleSize = 20
  const headingSize = 14
  const bodySize = 11
  const smallSize = 9
  
  // Title
  doc.setFontSize(titleSize)
  doc.setFont('helvetica', 'bold')
  doc.text('RECEIPT DOCUMENT', 105, 20, { align: 'center' })
  
  // Receipt ID and Date
  doc.setFontSize(headingSize)
  doc.setFont('helvetica', 'normal')
  doc.text(`Receipt ID: ${receipt.id}`, 20, 40)
  
  const receiptDate = receipt.created_at 
    ? new Date(receipt.created_at).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      })
    : 'N/A'
  
  doc.setFontSize(bodySize)
  doc.text(`Date: ${receiptDate}`, 20, 48)
  
  // Reference if available
  if (receipt.reference) {
    doc.text(`Reference: ${receipt.reference}`, 20, 56)
  }
  
  // Separator line
  doc.setLineWidth(0.5)
  doc.line(20, 65, 190, 65)
  
  // Receipt Details Section
  doc.setFontSize(headingSize)
  doc.setFont('helvetica', 'bold')
  doc.text('Receipt Details', 20, 75)
  
  doc.setFontSize(bodySize)
  doc.setFont('helvetica', 'normal')
  
  let yPos = 85
  
  // Product
  doc.setFont('helvetica', 'bold')
  doc.text('Product:', 20, yPos)
  doc.setFont('helvetica', 'normal')
  doc.text(productName, 60, yPos)
  yPos += 8
  
  // Quantity
  doc.setFont('helvetica', 'bold')
  doc.text('Quantity:', 20, yPos)
  doc.setFont('helvetica', 'normal')
  doc.text(`${receipt.quantity} units`, 60, yPos)
  yPos += 8
  
  // Warehouse
  if (warehouseName) {
    doc.setFont('helvetica', 'bold')
    doc.text('Warehouse:', 20, yPos)
    doc.setFont('helvetica', 'normal')
    doc.text(warehouseName, 60, yPos)
    yPos += 8
  }
  
  // Supplier
  if (supplierName || receipt.supplier) {
    doc.setFont('helvetica', 'bold')
    doc.text('Supplier:', 20, yPos)
    doc.setFont('helvetica', 'normal')
    doc.text(supplierName || receipt.supplier || 'N/A', 60, yPos)
    yPos += 8
  }
  
  // Note Section
  if (receipt.note) {
    yPos += 5
    doc.setLineWidth(0.5)
    doc.line(20, yPos, 190, yPos)
    yPos += 10
    
    doc.setFontSize(headingSize)
    doc.setFont('helvetica', 'bold')
    doc.text('Notes', 20, yPos)
    
    yPos += 8
    doc.setFontSize(bodySize)
    doc.setFont('helvetica', 'normal')
    
    // Handle multi-line notes
    const splitNote = doc.splitTextToSize(receipt.note, 170)
    doc.text(splitNote, 20, yPos)
    yPos += (splitNote.length * 6)
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(smallSize)
  doc.setFont('helvetica', 'italic')
  doc.text('Generated by CoreInventory System', 105, pageHeight - 20, { align: 'center' })
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 105, pageHeight - 15, { align: 'center' })
  
  // Save/Download PDF
  const fileName = `Receipt_${receipt.id}_${new Date().getTime()}.pdf`
  doc.save(fileName)
}

export function generateBulkReceiptsPDF(receipts: ReceiptPDFData[]): void {
  const doc = new jsPDF()
  
  receipts.forEach((receiptData, index) => {
    if (index > 0) {
      doc.addPage()
    }
    
    const { receipt, productName, warehouseName, supplierName } = receiptData
    
    // Similar structure as single receipt
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('RECEIPT DOCUMENT', 105, 20, { align: 'center' })
    
    doc.setFontSize(14)
    doc.setFont('helvetica', 'normal')
    doc.text(`Receipt ID: ${receipt.id}`, 20, 40)
    
    const receiptDate = receipt.created_at 
      ? new Date(receipt.created_at).toLocaleDateString()
      : 'N/A'
    
    doc.setFontSize(11)
    doc.text(`Date: ${receiptDate}`, 20, 48)
    
    doc.setLineWidth(0.5)
    doc.line(20, 55, 190, 55)
    
    let yPos = 65
    doc.text(`Product: ${productName}`, 20, yPos)
    yPos += 8
    doc.text(`Quantity: ${receipt.quantity} units`, 20, yPos)
    yPos += 8
    
    if (warehouseName) {
      doc.text(`Warehouse: ${warehouseName}`, 20, yPos)
      yPos += 8
    }
    
    if (supplierName || receipt.supplier) {
      doc.text(`Supplier: ${supplierName || receipt.supplier || 'N/A'}`, 20, yPos)
    }
  })
  
  const fileName = `Receipts_Batch_${new Date().getTime()}.pdf`
  doc.save(fileName)
}
